In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [4]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [5]:
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [6]:
df['stabf']= df['stabf'].replace('stable', 0)

In [7]:
df['stabf']= df['stabf'].replace('unstable', 1)

In [8]:
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,1
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,0
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,1
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,1
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,1

In [9]:
df=df.drop(columns = 'stab', axis = 1)

In [10]:
df.describe(include= 'all')

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.250000,5.250001,5.250004,5.249997,3.750000,-1.250000,-1.250000,-1.250000,0.525000,0.525000,0.525000,0.525000,0.638000
std,2.742548,2.742549,2.742549,2.742556,0.752160,0.433035,0.433035,0.433035,0.274256,0.274255,0.274255,0.274255,0.480603
min,0.500793,0.500141,0.500788,0.500473,1.582590,-1.999891,-1.999945,-1.999926,0.050009,0.050053,0.050054,0.050028,0.000000
25%,2.874892,2.875140,2.875522,2.874950,3.218300,-1.624901,-1.625025,-1.624960,0.287521,0.287552,0.287514,0.287494,0.000000
50%,5.250004,5.249981,5.249979,5.249734,3.751025,-1.249966,-1.249974,-1.250007,0.525009,0.525003,0.525015,0.525002,1.000000
75%,7.624690,7.624893,7.624948,7.624838,4.282420,-0.874977,-0.875043,-0.875065,0.762435,0.762490,0.762440,0.762433,1.000000
max,9.999469,9.999837,9.999450,9.999443,5.864418,-0.500108,-0.500072,-0.500025,0.999937,0.999944,0.999982,0.999930,1.000000

In [11]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [12]:
X = df.drop(columns='stabf')
y = df['stabf']

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
x_train.value_counts()

tau1      tau2      tau3      tau4      p1        p2         p3         p4         g1        g2        g3        g4
0.500793  6.734360  5.284357  5.797771  3.387591  -0.752656  -0.972783  -1.662152  0.802707  0.204237  0.642260  0.513210    1
6.818537  9.247272  6.467968  1.791262  2.382490  -0.800627  -0.869578  -0.712285  0.544314  0.727335  0.835718  0.846119    1
6.834973  2.009239  1.745053  3.232995  2.727052  -0.577740  -1.247042  -0.902269  0.086041  0.202660  0.357411  0.848714    1
6.833746  8.847534  5.509003  6.320948  4.367438  -1.703936  -1.280371  -1.383131  0.709491  0.430811  0.583490  0.313310    1
6.832938  8.103769  9.659373  1.107526  4.748096  -0.896783  -1.972358  -1.878956  0.539333  0.731171  0.466057  0.603674    1
                                                                                                                            ..
3.663306  3.777186  5.392658  0.902859  3.375034  -1.151822  -1.148057  -1.075154  0.272599  0.856673  0.820077  0.677774    1
3.659313  1.991381  1.637647  1.569817  3.292358  -1.237096  -0.893677  -1.161585  0.284699  0.797662  0.782697  0.307094    1
3.658601  3.823051  3.382791  2.025699  3.589800  -1.499432  -0.517879  -1.572490  0.767596  0.188279  0.154670  0.257087    1
3.656944  8.636556  6.177594  4.499886  4.082783  -1.450646  -1.068126  -1.564011  0.244680  0.645080  0.377655  0.665789    1
9.999469  5.677620  8.002448  7.360514  3.280473  -0.870700  -0.707238  -1.702536  0.584174  0.296674  0.710548  0.233335    1
Length: 8000, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)
#y_train= scaler.fit_transform(y_train)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = clf.predict(x_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.4f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(x_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_clf = RandomForestClassifier(random_state=1)
rf_clf.fit(x_train, y_train)
#pred = rf_clf.predict(x_test)
#print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.4f}%")

print_score(rf_clf, x_train, y_train, x_test, y_test, train=True)
print_score(rf_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 100.0000%
_______________________________________________
CLASSIFICATION REPORT:
                0       1  accuracy  macro avg  weighted avg
precision     1.0     1.0       1.0        1.0           1.0
recall        1.0     1.0       1.0        1.0           1.0
f1-score      1.0     1.0       1.0        1.0           1.0
support    2908.0  5092.0       1.0     8000.0        8000.0
_______________________________________________
Confusion Matrix:
 [[2908    0]
 [   0 5092]]

Test Result:
================================================
Accuracy Score: 92.80%
_______________________________________________
CLASSIFICATION REPORT:
                    0            1  accuracy    macro avg  weighted avg
precision    0.917647     0.933333     0.928     0.925490      0.927749
recall       0.876404     0.956522     0.928     0.916463      0.928000
f1-score     0.896552     0.944785     0.928     0.920669      0.927614
support    712.000000  1288.000000     0.928  2000.000000   2000.000000
_______________________________________________
Confusion Matrix:
 [[ 624   88]
 [  56 1232]]

In [17]:
from sklearn.ensemble import ExtraTreesClassifier

et_clf = ExtraTreesClassifier(random_state=1)
et_clf.fit(x_train, y_train)

print_score(et_clf, x_train, y_train, x_test, y_test, train=True)
print_score(et_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 100.0000%
_______________________________________________
CLASSIFICATION REPORT:
                0       1  accuracy  macro avg  weighted avg
precision     1.0     1.0       1.0        1.0           1.0
recall        1.0     1.0       1.0        1.0           1.0
f1-score      1.0     1.0       1.0        1.0           1.0
support    2908.0  5092.0       1.0     8000.0        8000.0
_______________________________________________
Confusion Matrix:
 [[2908    0]
 [   0 5092]]

Test Result:
================================================
Accuracy Score: 92.60%
_______________________________________________
CLASSIFICATION REPORT:
                    0            1  accuracy    macro avg  weighted avg
precision    0.940625     0.919118     0.926     0.929871      0.926774
recall       0.845506     0.970497     0.926     0.908001      0.926000
f1-score     0.890533     0.944109     0.926     0.917321      0.925036
support    712.000000  1288.000000     0.926  2000.000000   2000.000000
_______________________________________________
Confusion Matrix:
 [[ 602  110]
 [  38 1250]]

In [18]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(random_state=1)
xgb_clf.fit(x_train, y_train)

print_score(xgb_clf, x_train, y_train, x_test, y_test, train=True)
print_score(xgb_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 100.0000%
_______________________________________________
CLASSIFICATION REPORT:
                0       1  accuracy  macro avg  weighted avg
precision     1.0     1.0       1.0        1.0           1.0
recall        1.0     1.0       1.0        1.0           1.0
f1-score      1.0     1.0       1.0        1.0           1.0
support    2908.0  5092.0       1.0     8000.0        8000.0
_______________________________________________
Confusion Matrix:
 [[2908    0]
 [   0 5092]]

Test Result:
================================================
Accuracy Score: 94.60%
_______________________________________________
CLASSIFICATION REPORT:
                    0            1  accuracy    macro avg  weighted avg
precision    0.937681     0.950382     0.946     0.944031      0.945860
recall       0.908708     0.966615     0.946     0.937661      0.946000
f1-score     0.922967     0.958430     0.946     0.940698      0.945805
support    712.000000  1288.000000     0.946  2000.000000   2000.000000
_______________________________________________
Confusion Matrix:
 [[ 647   65]
 [  43 1245]]

In [19]:
import lightgbm as lgb
lgb_clf = lgb.LGBMClassifier(random_state=1)
lgb_clf.fit(x_train, y_train)

print_score(lgb_clf, x_train, y_train, x_test, y_test, train=True)
print_score(lgb_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 99.7875%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy    macro avg  weighted avg
precision     0.997590     0.998037  0.997875     0.997814      0.997875
recall        0.996561     0.998625  0.997875     0.997593      0.997875
f1-score      0.997076     0.998331  0.997875     0.997703      0.997875
support    2908.000000  5092.000000  0.997875  8000.000000   8000.000000
_______________________________________________
Confusion Matrix:
 [[2898   10]
 [   7 5085]]

Test Result:
================================================
Accuracy Score: 93.65%
_______________________________________________
CLASSIFICATION REPORT:
                    0            1  accuracy    macro avg  weighted avg
precision    0.925764     0.942117    0.9365     0.933941      0.936296
recall       0.893258     0.960404    0.9365     0.926831      0.936500
f1-score     0.909221     0.951173    0.9365     0.930197      0.936238
support    712.000000  1288.000000    0.9365  2000.000000   2000.000000
_______________________________________________
Confusion Matrix:
 [[ 636   76]
 [  51 1237]]